# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-tui" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "39f8cd7ccfcb40ced2e8127fc91fbdd5a0fd8d29c3171d5cf9165d1ec9621841"
      url "https://github.com/kurenn/slack-tui/releases/download/v#{version}/slack-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0a8bdbb6182f951656564fb1e17f97fec7baae3baed1d95d381d2a480f7abec"
      url "https://github.com/kurenn/slack-tui/releases/download/v#{version}/slack-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eff00c0132e7e9cc87c1934a5bdf37afdb36b97c027ef6c8803c9add3e61906a"
      url "https://github.com/kurenn/slack-tui/releases/download/v#{version}/slack-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8fe1954a7fbf4fb64d5774172710df610f791798b23ad258451f31e74270986"
      url "https://github.com/kurenn/slack-tui/releases/download/v#{version}/slack-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slack-tui"
  desc "A keyboard-first terminal Slack client"
  homepage "https://github.com/kurenn/slack-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-tui"

  # No zap stanza required

end
