# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackTui < Formula
  desc "A keyboard-first terminal Slack client"
  homepage "https://github.com/kurenn/slack-tui"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.1.2/slack-tui_0.1.2_darwin_amd64.tar.gz"
      sha256 "ebd3569cd042a3c21df2278c92d463ab60c0bf18f31f0f783d8abfe00a8abd65"

      define_method(:install) do
        bin.install "slack-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.1.2/slack-tui_0.1.2_darwin_arm64.tar.gz"
      sha256 "5b25b2217ee0206a8c341d32438e37bbc8dfe9f07644b1449f9a2781095505d1"

      define_method(:install) do
        bin.install "slack-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.1.2/slack-tui_0.1.2_linux_amd64.tar.gz"
      sha256 "17c5726f7896de2a5277e7bef4673d29249587bdb5560f6026dbc56f4931236f"
      define_method(:install) do
        bin.install "slack-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.1.2/slack-tui_0.1.2_linux_arm64.tar.gz"
      sha256 "92ef701346fa7928c2438bb9dfd042b14c3d2bd0c5b93070c93cc46c100ef12d"
      define_method(:install) do
        bin.install "slack-tui"
      end
    end
  end

  test do
    system "#{bin}/slack-tui", "--version"
  end
end
