# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackTui < Formula
  desc "A keyboard-first terminal Slack client"
  homepage "https://github.com/kurenn/slack-tui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.2.0/slack-tui_0.2.0_darwin_amd64.tar.gz"
      sha256 "ed0d7f3abc10137b03bf920cbd7c021fc85c0d4b55beb09dedb3c4ea959ec880"

      define_method(:install) do
        bin.install "slack-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.2.0/slack-tui_0.2.0_darwin_arm64.tar.gz"
      sha256 "5e6b30360a8afb9baac058c87229c479bc823b8bcabd04bae3892e74e5c1056c"

      define_method(:install) do
        bin.install "slack-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.2.0/slack-tui_0.2.0_linux_amd64.tar.gz"
      sha256 "4e64fdadbc97e4501e122c68666bf13abdf5021a81802c4ac0b2934a28fdc8c0"
      define_method(:install) do
        bin.install "slack-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurenn/slack-tui/releases/download/v0.2.0/slack-tui_0.2.0_linux_arm64.tar.gz"
      sha256 "e24ae42725cddaea8146ba0a6db27b309d2c5d403dca5c79989abc7093c67366"
      define_method(:install) do
        bin.install "slack-tui"
      end
    end
  end

  test do
    system "#{bin}/slack-tui", "--version"
  end
end
